### ISSUE TITLE
EVM-C improvements

### ISSUE THREAD

**Issue by chfast** [ethereum/evmjit#73]
- [x] Auto generate doxygen docs and push to GitHub Pages.
- [x] ~~`evm_get_info` should return NULL if the key is not found (by @axic)~~.
- [x] Drop `evm_get_info()`. (#84)
- [x] Consider extending `evm_result` with custom error codes and messages. (#81 and #83)
- [x] Support multiple VMs by providing vtable in `evm_instance`.
- [x] Replace `evmjit_is_code_ready()` by `evm_get_code_status()`.
- [x] Replace `evmjit_compile()` by `evm_prepare_code()`.
- [x] Consider not using `bool`.
- [x] Replace `#define EVM_EXCEPTION` with `const int64_t EVM_EXCEPTION` (will help Python CFFI).
- [x] Add API version to `evm_interface`.
- [x] ~~Reuse `evm_result`/`evm_result_code` in `evm_call_fn`.~~ (moved to #86)
- [x] ~~Add support for VM tracing.~~ (moved to https://github.com/ethereum/evmjit/issues/85)

**Comment by axic** [comment]
Can you also explain in the header how a client using EVM-C should handle the `evmjit_` methods?

I think it the case of Hera right now I should have them return `true` unconditionally, but a better name would make more sense for them.

**Comment by axic** [comment]
Probably the question is whether you want to have explicit differentiation between interpreted and JIT implementations or not.

If you don't want to make a distinction, the following API could be used:

```
instance = evm_create()

evm_compile(instance, code_hash, code)

while (not evm_is_code_ready(instance, code_hash))
  wait

// NOTE: execute only receives the code_hash and the input message details
evm_execute(instance, hash)

evm_destroy(instance)
```

This puts the burden on the implementation to keep a copy of the code in the `instance`. For JIT that is happening anyway.

Regarding caching:
- `evm_is_code_ready` (or `evm_is_code_hash_available`?) tells whether the code is available and is ready to be executed
- an implementation not wishing to keep cache, could remove the code for the `code_hash` after `evm_execute` has finished

**Comment by chfast** [comment]
Interpreters should return `false`, however it should not matter much.

They are somehow optional, but I don't think there is a nice way to provide default implementation. 

I plan to rename them to:

- `evmjit_is_code_ready()` to `evm_get_code_status()`. Default implementation should return 'UKNOWN'.
- `evmjit_compile()` to `evm_prepare_code()`. Default implementation should be empty.

**Comment by axic** [comment]
Another bit to decide: using `bool`. It is fine we specify that C99 is the required (which includes it in `stdbool.h`).

I'm in slight favour doing so.

Alternative way is to use `int` with `0` and `1`.

**Comment by axic** [comment]
I think we should use standard include guards in `evm.h` and not `#pragma once` as that is not C99 compatible. It is supported by the hybrid C/C++ compilers (gcc, clang) in C99 mode though.

**Comment by chfast** [comment]
I don't know a compiler what would not support it. We can be pedantic about it, but I prefer not. E.g. Python CFFI does not support `#if` at all so it has to be removed from the source.

**Comment by axic** [comment]
> I don't know a compiler what would not support it. 

Probably you're right - it is a bit down to preference. I've mostly came across the use of pragmas in C++ derived code or C code written by C++ developers.

We can probably assume though, that the compilers cpp-ethereum is compiled with need to understand pragmas anyway.

> E.g. Python CFFI does not support `#if` at all

It doesn't support `#if` as a preprocessor macro? That seems odd and very limiting.

**Comment by bobsummerwill** [comment]
`#pragma once` is pretty standard now (GCC, Clang and VC++), but it doesn't do much harm to have both that and `#ifdef/#ifndef` guards (old school).

CFFI cannot cope with pre-processor conditional at all?   Really?

**Comment by chfast** [comment]
CFFI parses C headers to get declarations. No preprocessor support.

**Comment by bobsummerwill** [comment]
Does it choke on them, though?   Or just ignore them, which is fine.

**Comment by chfast** [comment]
Chokes :)

**Comment by bobsummerwill** [comment]
What kind of monkey of a program would write a C parser which chokes on \#ifdefs?    Every C header file in the universe has \#ifdefs?

How hard is it to write:

    if (line.startswith("#if"))
        continue;

Well, I guess the solution is to have two levels of headers, and wrap one in the other?   Like an `.inc` file?

**Comment by chfast** [comment]
The solutions is to copy the header and prepare version specially for CFFI.

**Comment by bobsummerwill** [comment]
So copy-and-postprocess-and-here-you-fucking-go-you-stupid-tool?   Right.

**Comment by axic** [comment]
We could consider how much of the `evm_result` / `evm_result_code` should/could be shared with `evm_call_fn`.

**Comment by chfast** [comment]
Having `evm_call_fn` returning single int64 is quite useful but also introduces API complication.

There is a big TODO item to allow VM to execute whole call stack and returning some kind of state diff.
